name: neostation
description: Neotation - Emulation Hub

publish_to: "none" # Remove this line if you wish to publish to pub.dev

workspace:
  - packages/flutter_7zip
  - packages/flutter_soloud
  - packages/gamepads
  - packages/gamepads_android
  - packages/gamepads_darwin
  - packages/gamepads_linux
  - packages/gamepads_platform_interface
  - packages/gamepads_windows

version: 0.7.5+90

environment:
  sdk: '>=3.9.2'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^8.0.2
  provider: ^6.1.5+1
  battery_plus: ^7.0.0
  gamepads:
    path: packages/gamepads
  flutter_7zip:
    path: packages/flutter_7zip
  file_picker: ^10.3.3
  path: ^1.9.1
  path_provider: ^2.1.5
  video_player: ^2.10.0
  fvp: ^0.35.2
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  crypto: ^3.0.6
  archive: ^4.0.9
  web_socket_channel: ^3.0.3
  url_launcher: ^6.3.2
  widget_mask: ^1.0.0
  flutter_screenutil: 5.9.3
  window_manager: ^0.5.1
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.1
  pointycastle: ^4.0.0
  carousel_slider: ^5.1.1
  sqlite3: ^3.1.2
  fullscreen_window: ^1.2.1
  animated_toggle_switch: ^0.8.7
  marquee: ^2.3.0
  logger: ^2.6.2
  sub_screen: ^0.1.9
  flutter_soloud:
    path: packages/flutter_soloud
  audio_metadata_reader: ^1.4.2
  wakelock_plus: ^1.5.1
  flutter_localization: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"
  mocktail: ^1.0.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo-background.png"
  adaptive_icon_foreground: "assets/images/logo-foreground.png"
  adaptive_icon_monochrome: "assets/images/logo-monochrome.png"
  adaptive_icon_foreground_inset: 20
  min_sdk_android: 21 # android min sdk min:16, default 21 
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  linux:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emulators/
    - assets/images/gamepad/
    - assets/images/icons/
    - assets/images/music/
    - assets/data/
    - assets/systems/
    - assets/sounds/
  shaders:
    - assets/shaders/stripes.frag
    - assets/shaders/fluid.frag
    - assets/shaders/gif_player.frag
    - assets/shaders/music_visualizer.frag
    - assets/shaders/music_card_background.frag
#refresh2